model_name: "BBAutoAttack_scene_classifier"

data_dir: "../scene_classification_dataset"
model_save_path: "bb_auto_attack/BBAutoAttack_scene_classifier.pt"
config_save_path: "bb_auto_attack/BBAutoAttack_scene_classifier.json"

batch_size: 16
img_size: 224
learning_rate: 0.001

train_split: 0.8
epochs: 20

model_architecture: "resnet18"
pretrained: true
