model_name: "BBAutoAttack_scene_classifier"

data_dir: "bb_auto_attack/dataset"
model_save_path: "bb_collect_resources/BBCollectResources_scene_classifier.pt"
config_save_path: "bb_collect_resources/BBCollectResources_classifier.json"

batch_size: 16
img_size: 224
learning_rate: 0.001

train_split: 0.8
epochs: 20

model_architecture: "resnet18"
pretrained: true
