# 寻找对手状态配置文件
# 匹配对手界面的UI配置

# 状态基本信息
state_name: "finding_opponent"
description: "寻找对手状态，等待匹配完成进入攻击界面"

# 状态识别标识
indicators:
  required: ["attack"]          # 有attack按钮（已离开村庄）
  optional: 
    - "cancel_button"           # 取消匹配按钮
    - "searching_text"          # "Searching..." 文字
    - "loading_spinner"         # 加载动画
  forbidden: ["find_now"]       # 不能有村庄的find_now按钮

# 进入攻击状态的标识
attack_ready_indicators:
  any_of:                       # 检测到任一即可
    - "enemy_base"              # 敌方基地
    - "troop_panel"             # 部队面板
    - "battle_timer"            # 战斗计时器
    - "deploy_area"             # 部署区域
    - "surrender_button"        # 投降按钮

# 相对位置配置
relative_positions:
  # 取消按钮通常在右上角
  cancel_from_center: [200, -150]

# 固定位置配置  
fixed_positions:
  cancel_button: [0.85, 0.15]   # 右上角取消按钮
  retry_area: [0.5, 0.6]        # 重试点击区域

# 操作配置
actions:
  wait_for_match: true          # 等待匹配完成
  max_wait_time: 45             # 最大等待时间（秒）
  auto_retry: true              # 匹配失败自动重试
  
# 时间配置
timing:
  max_duration: 60              # 状态最大持续时间
  check_interval: 2.0           # 状态检查间隔
  retry_delay: 3.0              # 重试延迟
  cancel_delay: 1.0             # 取消后延迟

# 重试配置
retry:
  max_retries: 3                # 最大重试次数
  retry_conditions:             # 重试条件
    - "timeout"                 # 超时
    - "match_failed"            # 匹配失败
    - "stuck"                   # 界面卡住

# 超时处理
timeout_handling:
  action: "cancel_and_retry"    # 超时后的操作
  fallback: "return_village"    # 最终备用操作

# UI元素验证
element_validation:
  attack:
    min_confidence: 0.6
    position_range:             # 允许的位置范围（比例）
      x: [0.3, 0.7]
      y: [0.2, 0.8]
      
  cancel_button:
    min_confidence: 0.7
    expected_position: [0.85, 0.15]  # 预期位置
    tolerance: 0.1              # 位置容差

# 调试配置  
debug:
  log_wait_status: true         # 记录等待状态
  log_match_progress: true      # 记录匹配进度
  highlight_ready_indicators: true  # 高亮准备标识