# 村庄状态配置文件
# Builder Base村庄界面的UI配置

# 状态基本信息
state_name: "village"
description: "Builder Base村庄状态，寻找并点击Attack按钮"

# 状态识别标识
indicators:
  required: ["find_now"]        # 必须检测到的元素
  optional: ["attack"]          # 可选检测的元素
  forbidden: []                 # 不能出现的元素

# 相对位置配置（相对于基准元素的偏移像素）
relative_positions:
  # attack按钮相对于find_now按钮的位置
  attack_from_find_now: [0, -60]
  
# 固定位置配置（基于屏幕比例 0.0-1.0）  
fixed_positions:
  # 备用attack按钮位置
  attack_backup: [0.5, 0.35]
  # 通用点击区域
  safe_area: [0.5, 0.5]

# 任务配置 (按优先级排序)
tasks:
  start_attack:
    name: "开始攻击"
    description: "点击attack按钮开始攻击循环"
    priority: 10
    conditions:
      required_elements: ["attack"]
    enabled: true
    
  collect_resources:
    name: "收集资源" 
    description: "收集村庄中的资源"
    priority: 5
    conditions:
      any_of: ["collect_gold", "collect_elixir", "collect_dark_elixir"]
    enabled: true
    max_collections: 3            # 单次最多收集数量
    collection_interval: 0.5      # 收集间隔
    
  attack_by_find_now:
    name: "通过find_now攻击"
    description: "通过find_now按钮计算attack按钮位置"
    priority: 3
    conditions:
      required_elements: ["find_now"]
      forbidden_elements: ["attack"]  # 没有直接attack按钮时才用
    enabled: true
    
  wait:
    name: "等待"
    description: "等待新的机会出现" 
    priority: 1
    conditions: {}                # 无条件，总是可执行
    enabled: true
    wait_duration: 1.0

# 操作配置
actions:
  primary_action: "start_attack"   # 主要操作
  fallback_actions:               # 备用操作序列
    - "attack_by_find_now"        # 通过find_now计算位置
    - "wait"                      # 等待
    
# 时间配置
timing:
  max_duration: 30              # 状态最大持续时间（秒）
  click_delay: 0.1              # 点击后延迟
  state_transition_delay: 2.0   # 状态切换等待时间
  retry_interval: 1.0           # 重试间隔

# 重试配置
retry:
  max_retries: 3                # 最大重试次数
  retry_on_failure: true        # 失败时是否重试

# UI元素验证
element_validation:
  find_now:
    min_confidence: 0.6         # 最小置信度
    min_size: [60, 25]          # 最小尺寸 [width, height]
    max_size: [200, 80]         # 最大尺寸
    
  attack:
    min_confidence: 0.5
    min_size: [50, 20]
    max_size: [150, 70]

# 调试配置
debug:
  log_detections: true          # 记录检测结果
  log_clicks: true              # 记录点击操作
  highlight_indicators: true    # 高亮标识元素